[{if $basketitem && $basketitem->getPersParams() && method_exists($basketitem, 'fcHasK3Configuration') && $basketitem->fcHasK3Configuration()}]
    [{foreach from=$basketitem->fcGetK3Configuration() item=aParam key=sVar}]
        [{if $sVar == 'code'}] Konfiguration-ID: [{$aParam}]
        [{elseif $sVar == 'app'}] AppCode: [{$aParam}]
        [{elseif $sVar == 'variables'}]
            [{foreach from=$aParam item=variable}]
                [{$variable.label}] : [{$variable.value}]
            [{/foreach}]
        [{/if}]
    [{/foreach}]
[{else}]
    [{$smarty.block.parent}]
[{/if}]